version: "3.7"

services:
  app:
    &default
    image: node:16.15.1
    working_dir: /app/
    command: npm run dev
    environment:
      REDIS_HOST: redis
      WEB_HOST: https://github.com/status
      DATABASE_HOST: postgresql
    volumes:
      - .:/app
    ports:
      - 8888:8888
    depends_on:
      - redis
      - memcache
      - dynamodb
      - postgresql

  #the services below is a short hand to use npm in docker context
  test:
    <<: *default
    command: npm run test
    ports: []

  lint:
    <<: *default
    command: npm run lint
    ports: []
    depends_on: []

  format:
    <<: *default
    command: npm run format
    ports: []
    depends_on: []

  redis:
    image: redis
    ports:
      - 6379:6379

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
